In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from math import sqrt
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [34]:
data = pd.read_csv('/Users/jeronimoperezrocha/Library/Containers/com.microsoft.Excel/Data/Downloads/environmental_data.csv')

In [35]:
data.head()


ImageID  GreenCover  WaterBodies    BuiltUp    Elevation  \
0        1   37.454012    18.513293  44.032695  1177.675577   
1        2   95.071431    54.190095 -49.261525  1111.404596   
2        3   73.199394    87.294584 -60.493978  4078.145612   
3        4   59.865848    73.222489 -33.088337  1122.957899   
4        5   15.601864    80.656115   3.742021  1223.773768   

   AverageTemperature DeforestationRisk  
0           23.635150            Medium  
1           29.834070            Medium  
2            2.523395            Medium  
3           21.243705            Medium  
4           18.587299            Medium

In [36]:
data.isnull().sum()

ImageID               0
GreenCover            0
WaterBodies           0
BuiltUp               0
Elevation             0
AverageTemperature    0
DeforestationRisk     0
dtype: int64

In [37]:
#dummy variables for deforestation_risk
deforestation_risk = {'Low':0, 'Medium':1, 'High':2}
data['DeforestationRisk'] = data['DeforestationRisk'].replace(deforestation_risk)

In [38]:
#Clusters
kmeans = KMeans(n_clusters=9)
kmeans.fit(data)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=9)

In [39]:
data['Cluster'] = kmeans.predict(data)

In [40]:
clusters = data.groupby('Cluster').mean()

In [41]:
clusters

ImageID  GreenCover  WaterBodies   BuiltUp    Elevation  \
Cluster                                                               
0        705.761905   51.550588    48.759156 -0.309745  4246.939844   
1        500.596386   52.054650    51.684047 -3.738697  1274.937954   
2        435.160839   51.566774    48.056894  0.376332  2881.963450   
3        740.631579   44.787645    53.272401  1.939953   375.864825   
4        741.320755   48.322614    47.768601  3.908785  2007.614978   
5        740.764151   45.088069    51.432105  3.479826  3470.235438   
6        233.132653   50.967110    47.572356  1.460534   447.436420   
7        215.018868   49.815110    58.203250 -8.018360  3903.657376   
8        237.385417   44.257794    49.442555  6.299651  2149.235349   

         AverageTemperature  DeforestationRisk  
Cluster                                         
0                 15.476554           1.630952  
1                 14.375030           1.000000  
2                 14.767062           1.160839  
3                 14.816064           1.284211  
4                 13.342419           1.009434  
5                 13.189388           1.669811  
6                 15.010567           1.244898  
7                 13.902903           1.566038  
8                 16.209752           1.020833

In [46]:
#define x and y
x = data[['AverageTemperature', 'GreenCover', 'DeforestationRisk', 'BuiltUp', 'WaterBodies']]
y = data['DeforestationRisk']

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=50)

In [48]:
for model in [LogisticRegression(), KNeighborsClassifier(), SVC()]:
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(model)
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Accuracy Score:\n", accuracy_score(y_test,y_pred))
    print()
    

LogisticRegression()
Confusion Matrix:
 [[ 29   0   0]
 [  0 145   0]
 [  0   0  76]]
Accuracy Score:
 1.0

KNeighborsClassifier()
Confusion Matrix:
 [[  5  18   6]
 [  9 104  32]
 [  6  33  37]]
Accuracy Score:
 0.584

SVC()
Confusion Matrix:
 [[  0  26   3]
 [  0 104  41]
 [  0  30  46]]
Accuracy Score:
 0.6


In [45]:
#random forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [28]:
model = RandomForestClassifier(n_estimators=1) #n_estimators is the number of trees in the forest
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Accuracy Score:\n", accuracy_score(y_test,y_pred))
print()

Confusion Matrix:
 [[ 15   0   0]
 [  0 107   0]
 [  0   0  78]]
Accuracy Score:
 1.0


for the first part of the analysis, I used the KMeans algorithm to cluster the data into 5 clusters. I then used the mean of each cluster to identify the characteristics of each cluster. I then used the clusters as a target variable to predict the deforestation risk. I used the following models: Logistic Regression, K-Nearest Neighbors, Support Vector Machine, and Random Forest. My Logistic Regression and Random Forest were overfitting. For the KNeighbors and Support Vector Machine, I got an accuracy of 0.6, respectively. I used test_size=0.20 and random_state=42. changing this might change the accuracy of the model. 

 